package org.pjr.rulesengine;

public class CommonConstants {

	public static final String QUERY_FETCHRULE_SELECTRULE="RE_FETCHRULE_SELECTRULE";
	public static final String QUERY_FETCHRULE_SELECTRULELOGIC = "RE_FETCHRULE_SELECTRULELOGIC";
	public static final String QUERY_FETCHALLRULES_SELECT="RE_FETCHALLRULES_SELECT";
	public static final String QUERY_FETCHALLRULES_SELECT_BYMODEL="RE_FETCHALLRULES_SELECT_BYMODEL";
	public static final String QUERY_FETCH_MODEL_BYNAME="RE_FETCHMODELBYNAME_SELECT";
	public static final String QUERY_FETCHSUBRULE_SELECT="RE_FETCHSUBRULE_SELECT";
	public static final String QUERY_FETCHSUBRULE_SELECTLOGIC="RE_FETCHSUBRULE_SELECTLOGIC";
}
