--db cLEAN UP
--Tables
DROP TABLE RE_OBECT_ATTR  cascade constraints;
DROP TABLE RE_OPERATOR  cascade constraints;
DROP TABLE RE_RULE_LOGIC  cascade constraints;
DROP TABLE RE_RULES  cascade constraints;
DROP TABLE RE_RULES_OPR_MAPPING  cascade constraints;
DROP TABLE RE_RULES_SUBRULE_MAPPING  cascade constraints;
DROP TABLE RE_SUBRULE  cascade constraints;
DROP TABLE RE_SUBRULE_ATTR_MAPPING  cascade constraints;
DROP TABLE RE_SUBRULE_LOGIC  cascade constraints;
DROP TABLE RE_SUBRULE_OPR_MAPPING  cascade constraints;
DROP TABLE USER_ADMIN  cascade constraints;
DROP TABLE RE_MODEL_CLASS  cascade constraints;

--Sequences
 --SEQUENCES
DROP SEQUENCE CONDITIONS_OPERATOR_MAPPING_SQ;
DROP SEQUENCE ATTR_PK_SQ;
DROP SEQUENCE CONDITIONS_SQ;
DROP SEQUENCE RE_RULES_PK_SQ;
DROP SEQUENCE SUBRULES_PK_SQ;
DROP SEQUENCE PROPERTY_OPERATOR_LIST_PK_SQ;
DROP SEQUENCE RULES_CONDITION_MAPPING_SQ;
DROP SEQUENCE RULES_OPR_MAPPING_PK_SQ;
DROP SEQUENCE RULES_SUBRULE_MAPPING_PK_SQ;
DROP SEQUENCE RULE_LOGIC_PK_SQ;
DROP SEQUENCE SUBRULE_ATTR_MAPPING_PK_SQ;
DROP SEQUENCE SUBRULE_LOGIC_PK_SQ;
DROP SEQUENCE SUBRULE_OPR_MAPPING_PK_SQ;
DROP SEQUENCE MODEL_CLASS_PK_SQ ;
COMMIT;

