


CREATE TABLE RE_OBECT_ATTR 
    ( 
     ATTR_ID VARCHAR2 (5 BYTE)  NOT NULL , 
     ATTR_NAME VARCHAR2 (30 BYTE)  NOT NULL , 
     ATTR_VALUE VARCHAR2 (30 BYTE)  NOT NULL 
    ) 
        TABLESPACE USERS 
        LOGGING 
;



ALTER TABLE RE_OBECT_ATTR 
    ADD CONSTRAINT ATTR_PRMKEY PRIMARY KEY ( ATTR_ID ) ;



CREATE TABLE RE_OPERATOR 
    ( 
     OPERATOR_ID VARCHAR2 (5 BYTE)  NOT NULL , 
     OPERATOR_NAME VARCHAR2 (30 BYTE)  NOT NULL , 
     OPERATOR_VALUE VARCHAR2 (30 BYTE)  NOT NULL 
    ) 
        TABLESPACE USERS 
        LOGGING 
;



ALTER TABLE RE_OPERATOR 
    ADD CONSTRAINT PROPERTY_OPERATOR_LIST_PRMKEY PRIMARY KEY ( OPERATOR_ID ) ;



CREATE TABLE RE_RULES 
    ( 
     RULE_ID VARCHAR2 (5 BYTE)  NOT NULL , 
     RULE_NAME VARCHAR2 (100 BYTE) , 
     RULE_DESCRIPTION VARCHAR2 (1000 BYTE) , 
     ACTIVE NUMBER  NOT NULL , 
     DEFAULT_VALUE VARCHAR2 (20 BYTE) , 
     EXE_ORDER NUMBER , 
     RETURN_VALUE VARCHAR2 (20 BYTE) 
    ) 
        TABLESPACE USERS 
        LOGGING 
;



ALTER TABLE RE_RULES 
    ADD CONSTRAINT RE_RULES_PRMKEY PRIMARY KEY ( RULE_ID ) ;


ALTER TABLE RE_RULES 
    ADD CONSTRAINT RULE_EXE_ORDER_UNIQUE UNIQUE ( EXE_ORDER ) ;



CREATE TABLE RE_RULES_OPR_MAPPING 
    ( 
     RULES_OPERATOR_ID VARCHAR2 (5 BYTE)  NOT NULL , 
     RULE_ID VARCHAR2 (5 BYTE)  NOT NULL , 
     OPERATOR_ID VARCHAR2 (5 BYTE)  NOT NULL 
    ) 
        TABLESPACE USERS 
        LOGGING 
;



ALTER TABLE RE_RULES_OPR_MAPPING 
    ADD CONSTRAINT RULES_OPR_MAPPING_PRMKEY PRIMARY KEY ( RULES_OPERATOR_ID ) ;



CREATE TABLE RE_RULES_SUBRULE_MAPPING 
    ( 
     RULE_SUBRULE_ID VARCHAR2 (5 BYTE)  NOT NULL , 
     RULE_ID VARCHAR2 (5 BYTE)  NOT NULL , 
     SUBRULE_ID VARCHAR2 (5 BYTE)  NOT NULL 
    ) 
        TABLESPACE USERS 
        LOGGING 
;



ALTER TABLE RE_RULES_SUBRULE_MAPPING 
    ADD CONSTRAINT RULES_SUBRULE_MAPPING_PRMKEY PRIMARY KEY ( RULE_SUBRULE_ID ) ;


ALTER TABLE RE_RULES_SUBRULE_MAPPING 
    ADD CONSTRAINT RULE_SUBRULE_UNIQUE UNIQUE ( RULE_ID , SUBRULE_ID ) ;



CREATE TABLE RE_RULE_LOGIC 
    ( 
     RULE_LOGIC_ID VARCHAR2 (5 BYTE)  NOT NULL , 
     RULE_ID VARCHAR2 (5 BYTE)  NOT NULL , 
     RULE_SUBRULE_MAP_ID VARCHAR2 (5 BYTE) , 
     RULE_OPERATOR_MAP_ID VARCHAR2 (5 BYTE) , 
     ORDER_NO NUMBER  NOT NULL 
    ) 
        TABLESPACE USERS 
        LOGGING 
;



ALTER TABLE RE_RULE_LOGIC 
    ADD CONSTRAINT RULE_LOGIC_PRMKEY PRIMARY KEY ( RULE_LOGIC_ID ) ;



CREATE TABLE RE_SUBRULE 
    ( 
     SUBRULE_ID VARCHAR2 (5 BYTE)  NOT NULL , 
     SUBRULE_NAME VARCHAR2 (100 BYTE)  NOT NULL , 
     SUBRULE_DESCRIPTION VARCHAR2 (1000 BYTE) , 
     DEFAULT_VALUE NUMBER  NOT NULL , 
     ACTIVE NUMBER  NOT NULL 
    ) 
        TABLESPACE USERS 
        LOGGING 
;



ALTER TABLE RE_SUBRULE 
    ADD CONSTRAINT SUBRULES_PRMKEY PRIMARY KEY ( SUBRULE_ID ) ;



CREATE TABLE RE_SUBRULE_ATTR_MAPPING 
    ( 
     SUBRULE_ATTR_ID VARCHAR2 (5 BYTE)  NOT NULL , 
     SUBRULE_ID VARCHAR2 (5 BYTE)  NOT NULL , 
     ATTR_ID VARCHAR2 (5 BYTE)  NOT NULL 
    ) 
        TABLESPACE USERS 
        LOGGING 
;



ALTER TABLE RE_SUBRULE_ATTR_MAPPING 
    ADD CONSTRAINT SUBRULE_ATTR_MAPPING_PRMKEY PRIMARY KEY ( SUBRULE_ATTR_ID ) ;



CREATE TABLE RE_SUBRULE_LOGIC 
    ( 
     SUBRULE_LOGIC_ID VARCHAR2 (5 BYTE)  NOT NULL , 
     SUBRULE_ID VARCHAR2 (5 BYTE)  NOT NULL , 
     SUBRULES_OPERATOR_ID VARCHAR2 (5 BYTE) , 
     SUBRULE_ATTR_ID VARCHAR2 (5 BYTE) , 
     ORDER_NO NUMBER  NOT NULL 
    ) 
        TABLESPACE USERS 
        LOGGING 
;



ALTER TABLE RE_SUBRULE_LOGIC 
    ADD CONSTRAINT SUBRULE_LOGIC_PRMKEY PRIMARY KEY ( SUBRULE_LOGIC_ID ) ;



CREATE TABLE RE_SUBRULE_OPR_MAPPING 
    ( 
     SUBRULE_OPERATOR_ID VARCHAR2 (5 BYTE)  NOT NULL , 
     SUBRULE_ID VARCHAR2 (5 BYTE)  NOT NULL , 
     OPERATOR_ID VARCHAR2 (5 BYTE)  NOT NULL 
    ) 
        TABLESPACE USERS 
        LOGGING 
;



ALTER TABLE RE_SUBRULE_OPR_MAPPING 
    ADD CONSTRAINT SUBRULE_OPR_MAPPING_PRMKEY PRIMARY KEY ( SUBRULE_OPERATOR_ID ) ;




ALTER TABLE RE_RULES_OPR_MAPPING 
    ADD CONSTRAINT RULES_OPR_MAPPING_OPR_FRK FOREIGN KEY 
    ( 
     OPERATOR_ID
    ) 
    REFERENCES RE_OPERATOR 
    ( 
     OPERATOR_ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE RE_RULES_OPR_MAPPING 
    ADD CONSTRAINT RULES_OPR_MAPPING_RUL_FRK FOREIGN KEY 
    ( 
     RULE_ID
    ) 
    REFERENCES RE_RULES 
    ( 
     RULE_ID
    ) 
    ON DELETE CASCADE 
    NOT DEFERRABLE 
;


ALTER TABLE RE_RULES_SUBRULE_MAPPING 
    ADD CONSTRAINT RULES_SUBRULE_MAPPING_FRK1 FOREIGN KEY 
    ( 
     RULE_ID
    ) 
    REFERENCES RE_RULES 
    ( 
     RULE_ID
    ) 
    ON DELETE CASCADE 
    NOT DEFERRABLE 
;


ALTER TABLE RE_RULES_SUBRULE_MAPPING 
    ADD CONSTRAINT RULES_SUBRULE_MAPPING_FRK2 FOREIGN KEY 
    ( 
     SUBRULE_ID
    ) 
    REFERENCES RE_SUBRULE 
    ( 
     SUBRULE_ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE RE_RULE_LOGIC 
    ADD CONSTRAINT RULE_LOGIC_OPR_MAPPING_FRK FOREIGN KEY 
    ( 
     RULE_OPERATOR_MAP_ID
    ) 
    REFERENCES RE_RULES_OPR_MAPPING 
    ( 
     RULES_OPERATOR_ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE RE_RULE_LOGIC 
    ADD CONSTRAINT RULE_LOGIC_SU_MAPPING_FRK FOREIGN KEY 
    ( 
     RULE_SUBRULE_MAP_ID
    ) 
    REFERENCES RE_RULES_SUBRULE_MAPPING 
    ( 
     RULE_SUBRULE_ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE RE_RULE_LOGIC 
    ADD CONSTRAINT RULE_LOGIC_SU_MAPPING_PRMKEY FOREIGN KEY 
    ( 
     RULE_ID
    ) 
    REFERENCES RE_RULES 
    ( 
     RULE_ID
    ) 
    ON DELETE CASCADE 
    NOT DEFERRABLE 
;


ALTER TABLE RE_SUBRULE_ATTR_MAPPING 
    ADD CONSTRAINT SUBRULE_ATTR_MAPPING_FRK1 FOREIGN KEY 
    ( 
     SUBRULE_ID
    ) 
    REFERENCES RE_SUBRULE 
    ( 
     SUBRULE_ID
    ) 
    ON DELETE CASCADE 
    NOT DEFERRABLE 
;


ALTER TABLE RE_SUBRULE_ATTR_MAPPING 
    ADD CONSTRAINT SUBRULE_ATTR_MAPPING_FRK2 FOREIGN KEY 
    ( 
     ATTR_ID
    ) 
    REFERENCES RE_OBECT_ATTR 
    ( 
     ATTR_ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE RE_SUBRULE_LOGIC 
    ADD CONSTRAINT SUBRULE_LOGIC_ATTR_MAPPING_FRK FOREIGN KEY 
    ( 
     SUBRULE_ATTR_ID
    ) 
    REFERENCES RE_SUBRULE_ATTR_MAPPING 
    ( 
     SUBRULE_ATTR_ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE RE_SUBRULE_LOGIC 
    ADD CONSTRAINT SUBRULE_LOGIC_OPR_MAPPING_FRK FOREIGN KEY 
    ( 
     SUBRULES_OPERATOR_ID
    ) 
    REFERENCES RE_SUBRULE_OPR_MAPPING 
    ( 
     SUBRULE_OPERATOR_ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE RE_SUBRULE_LOGIC 
    ADD CONSTRAINT SUBRULE_LOGIC_SU_MAPPING_FRK FOREIGN KEY 
    ( 
     SUBRULE_ID
    ) 
    REFERENCES RE_SUBRULE 
    ( 
     SUBRULE_ID
    ) 
    ON DELETE CASCADE 
    NOT DEFERRABLE 
;


ALTER TABLE RE_SUBRULE_OPR_MAPPING 
    ADD CONSTRAINT SUBRULE_OPR_MAPPING_FRK FOREIGN KEY 
    ( 
     OPERATOR_ID
    ) 
    REFERENCES RE_OPERATOR 
    ( 
     OPERATOR_ID
    ) 
    NOT DEFERRABLE 
;


ALTER TABLE RE_SUBRULE_OPR_MAPPING 
    ADD CONSTRAINT SUBRULE_OPR_MAPPING_FRK1 FOREIGN KEY 
    ( 
     SUBRULE_ID
    ) 
    REFERENCES RE_SUBRULE 
    ( 
     SUBRULE_ID
    ) 
    ON DELETE CASCADE 
    NOT DEFERRABLE 
;


--------------------------------------------------------
--  DDL for Table USER_ADMIN
--------------------------------------------------------

  CREATE TABLE USER_ADMIN 
   (	"USER_ID" VARCHAR2(20 BYTE), 
	"ACTIVE" NUMBER, 
	"ENABLE_DATE" DATE, 
	"DISABLE_DATE" DATE, 
	"ISADMIN" NUMBER, 
	"PASSWORD" VARCHAR2(100 BYTE)
   ) 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USER_ADMIN
--------------------------------------------------------

  ALTER TABLE USER_ADMIN MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE USER_ADMIN MODIFY ("ACTIVE" NOT NULL ENABLE);
 
  ALTER TABLE USER_ADMIN MODIFY ("ISADMIN" NOT NULL ENABLE);

  
  
  --SEQUENCES
CREATE SEQUENCE CONDITIONS_OPERATOR_MAPPING_SQ 
    INCREMENT BY 1 
    START WITH 2000
    MAXVALUE 999999999999999999999999999 
    MINVALUE 1 
    NOCACHE 
;
CREATE SEQUENCE ATTR_PK_SQ 
    INCREMENT BY 1 
    START WITH 2000
    MAXVALUE 999999999999999999999999999 
    MINVALUE 1000 
    NOCACHE 
;
CREATE SEQUENCE CONDITIONS_SQ 
    INCREMENT BY 1 
    START WITH 2000
    MAXVALUE 999999999999999999999999999 
    MINVALUE 1 
    NOCACHE 
;
CREATE SEQUENCE RE_RULES_PK_SQ 
    INCREMENT BY 1 
    START WITH 2000
    MAXVALUE 999999999999999999999999999 
    MINVALUE 1 
    NOCACHE 
;
CREATE SEQUENCE SUBRULES_PK_SQ 
    INCREMENT BY 1 
    START WITH 2000
    MAXVALUE 999999999999999999999999999 
    MINVALUE 1 
    NOCACHE 
;
CREATE SEQUENCE PROPERTY_OPERATOR_LIST_PK_SQ 
    INCREMENT BY 1 
    START WITH 2000
    MAXVALUE 999999999999999999999999999 
    MINVALUE 1000 
    NOCACHE 
;
CREATE SEQUENCE RULES_CONDITION_MAPPING_SQ 
    INCREMENT BY 1 
    START WITH 2000
    MAXVALUE 999999999999999999999999999 
    MINVALUE 1 
    NOCACHE 
;
CREATE SEQUENCE RULES_OPR_MAPPING_PK_SQ 
    INCREMENT BY 1
    START WITH 2000
    MAXVALUE 999999999999999999999999999 
    MINVALUE 1 
    NOCACHE 
;
CREATE SEQUENCE RULES_SUBRULE_MAPPING_PK_SQ 
    INCREMENT BY 1 
    START WITH 2000
    MAXVALUE 999999999999999999999999999 
    MINVALUE 1 
    NOCACHE 
;
CREATE SEQUENCE RULE_LOGIC_PK_SQ 
    INCREMENT BY 1
    START WITH 2000
    MAXVALUE 999999999999999999999999999 
    MINVALUE 1 
    NOCACHE 
;
CREATE SEQUENCE SUBRULE_ATTR_MAPPING_PK_SQ 
    INCREMENT BY 1 
    START WITH 2000
    MAXVALUE 999999999999999999999999999 
    MINVALUE 1 
    NOCACHE 
;
CREATE SEQUENCE SUBRULE_LOGIC_PK_SQ 
    INCREMENT BY 1 
    START WITH 2000
    MAXVALUE 999999999999999999999999999 
    MINVALUE 1 
    NOCACHE 
;
CREATE SEQUENCE SUBRULE_OPR_MAPPING_PK_SQ 
    INCREMENT BY 1 
    START WITH 2000
    MAXVALUE 999999999999999999999999999 
    MINVALUE 1 
    NOCACHE 
;